### PR TITLE
Add measure command

### PR DESCRIPTION
**Pull request by aycabta**
You can use `measure` command to check performance in IRB like below:

```
irb(main):001:0> 3
=> 3
irb(main):002:0> measure
TIME is added.
=> nil
irb(main):003:0> 3
processing time: 0.000058s
=> 3
irb(main):004:0> measure :off
=> nil
irb(main):005:0> 3
=> 3
```

You can set `measure :on` by `IRB.conf[:MEASURE] = true` in .irbrc, and, also, set custom performance check method:

```ruby
IRB.conf[:MEASURE_PROC][:CUSTOM] = proc { |context, code, line_no, &block|
  time = Time.now
  result = block.()
  now = Time.now
  puts 'custom processing time: %fs' % (Time.now - time) if IRB.conf[:MEASURE]
  result
}
```

### CODE REVIEW

**Comment by ko1** [comment]
`MEASURE_MODE` like `IRB.conf[:PROMPT_MODE] = :DEFAULT` ? (nil by default disables the measurement)

**Comment by ko1** [comment]
or it can be stack-able (measure time, memory, ...) different from prompt.

**Comment by aycabta** [comment]
Most of the measurements will affect each other. Also, if IRB makes multiple executions for each measuring, code with side effects will not be measured correctly, and execution time will be longer. Therefore, I don't think the stackable way is possible.

**Comment by aycabta** [comment]
I thought about it again, and I think stackable is possible, so I implemented it.

**Pull request merged**
